name: KBase JobRunner tests

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
  push:
    # run workflow when merging to main or develop
    branches:
      - main
      - master
      - develop
      - scanon/gha

jobs:

  jobsrunner_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - name: Install Docker
      uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12
    
    - name: Repo checkout
      uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependecies
      # tried VaultVulp/action-pipenv but pytest wasn't on the path post action
      shell: bash
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install mock-server
        make mock
        docker pull kbase/runtester
        docker tag kbase/runtester test/runtester
        curl -q -L -o $HOME/cromwell-44.jar https://github.com/broadinstitute/cromwell/releases/download/44/cromwell-44.jar
        touch ~/cromwell.conf
     

    - name: Run tests
      shell: bash
      run: |
        export KB_AUTH_TOKEN=bogus
        export KB_ADMIN_AUTH_TOKEN=bogus
        export KB_BASE_URL=https://ci.kbase.us/services
        IP=$(curl https://api.ipify.org)
        export TEST_URL="$IP:8888"
        mock-server --dir=./test/mock-server --address=0.0.0.0 &
        make test

    - name: Failure logs
      if: ${{ failure() }}
      shell: bash
      run: |
        find /tmp

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
